Updated MasterDetailPageRenderer
Fix to Objectdisposed crash when closing app
Description of Change
I put the test IsDisposed instead of just call RemoveDrawerListener
Bugs Fixed
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer'.